
CREATE TABLE _chickpea_testing (id INT UNSIGNED NOT NULL AUTO_INCREMENT, ,create_date TIMESTAMP NOT NULL,PRIMARY KEY ( id ) )
-----
CREATE TABLE chickpea_test_people (id INT UNSIGNED NOT NULL AUTO_INCREMENT,title VARCHAR( 300 ),email VARCHAR( 300 ),content TEXT NOT NULL ,create_date TIMESTAMP NOT NULL,PRIMARY KEY ( id ) )
-----
