<?php
include 'base.php';

class db extends Base
{

    private $_fields = array ();
    private $_name;

    private $_query;

    public function __Construct ( $name, $fields )
    {
        parent::__Construct ();

        $this->_name = $name;
        $this->_fields = $fields;

        $this->check_functions ();
        $this->check_database ();
    }

    /**
     * Method to connect to mysql
     *
     * @access public
     */
    public function connect_mysql ()
    {
        mysql_connect ( $this->_db_host, $this->_db_user, $this->_db_pass ) or die ( mysql_error () );
        $db_exists = mysql_select_db ( $this->_db_name ) or die ( mysql_error () );

        if (!$db_exists) {
            mysql_query ( "CREATE DATABASE " . $this->_db_name ) or die ( mysql_error () );
            mysql_select_db ( $this->_db_name ) or die ( mysql_error () );
        }
    }

    /**
     * Method to create the table
     * Checks if the table already exists, if not it is created
     *
     * @access public
     */
    public function check_exists ()
    {
        $table_exists_query = mysql_query ( "SHOW TABLES LIKE '" . $this->_db_name . "_" . $this->_name . "'" );
        $exists_count = mysql_num_rows ( $table_exists_query );

        if ($exists_count > 0) {
            display ( 'The table called ' . $this->_db_name . '_' . $this->_name . ' already exists.\n\nThe script will now end.\n\n' );
            die (0);
        }
    }

    /**
     * Method to create the query that will create the table
     * Rows will be taken from the array created the view
     *
     * @access public
     */
    public function get_query ()
    {
        $query = "CREATE TABLE `" . $this->_db_name . "_" . $this->_name . "` (
        `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY ";

        if ( count ( $this->_fields ) > 0 ) {
            $query .= ', ';

            $i = 1;
            foreach ($this->_fields as $data) {
                switch ($data['mysql_type']) {
                    case ( 'int' ) :
                        $default = '( 20 )';
                    break;

                    case ( 'varchar' ) :
                        $default = '( 255 )';
                    break;

                    default :
                        $default = '';
                }

                $query .= " `" . $this->_db_name . "_" . $this->_name . "_" . strtolower ( $data['name'] ) . "` " . strtoupper ( $data['mysql_type'] ) . " " . ( !!$data['max_length'] ? '(' . $data['max_length'] . ')' : $default ) . ", ";

                $i++;
            }

            $query .= "`" . $this->_db_name . "_" . $this->_name . "_image_id` INT(11),
            `create_date` timestamp";
        }

        $query .= ')';

        $this->_query = $query;
    }

    /**
     * Method to run the query generated by the get_query method
     *
     * @access public
     */
    public function create_table ()
    {
        if ( mysql_query ( $this->_query ) or die ( mysql_error () ) )
            display ( "\nTable created successfully\n" );

        else {
            display ( "\nTable could not created\nQuery:\n\n " . $this->_query . " \n\nThe script will now end\n\n" );
            die (0);
        }
    }

    /**
     * Method to check if the image table exists
     * If it does dont do anything
     * If it doesnt create the table and the model if it doesnt already exist
     *
     * @access public
     */
    public function image_table ()
    {
        $images_exists_query = mysql_query ( "SHOW TABLES LIKE '" . $this->_db_name . "_image'" );
        $images_exists_count = mysql_num_rows ( $images_exists_query );

        if ($images_exists_count === 0) {
            mysql_query ( 'CREATE TABLE `' . $this->_db_name . '_image` (
            `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            `' . $this->_db_name . '_image_imgname` VARCHAR(255),
            `' . $this->_db_name . '_image_create_date` timestamp )' ) or die ( mysql_error () );
        }

        if ( !file_exists ( '../app/models/image/image_model.php' ) ) {
            $image_model = '<?php

class image_model extends active_record
{

}

?>';

            mkdir ( '../app/models/image/' );
            file_put_contents ( '../app/models/image/image_model.php', $image_model );

            display ( "\nImage table and model has been made.\n" );
        }
    }

    /**
     * Method to check if the image relationship table exists
     * If it doesnt exist then it will be created, the model will also be created if it doesnt exist
     *
     * @access public
     */
    public function image_relationship_table ()
    {
        //Set up the query to make the image_relationship table if it doesnt already exist
        $ir_exists_query = mysql_query ( "SHOW TABLES LIKE '" . $this->_db_name . "_image_relationship'" );
        $ir_exists_count = mysql_num_rows ( $ir_exists_query );

        if ($ir_exists_count === 0) {
            mysql_query ( 'CREATE TABLE `' . $this->_db_name . '_image_relationship` (
            `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            `' . $this->_db_name . '_image_relationship_owner_id` INT(11),
            `' . $this->_db_name . '_image_relationship_image_id` INT(11),
            `' . $this->_db_name . '_image_relationship_type` VARCHAR(255),
            `create_date` timestamp )' ) or die ( mysql_error () );

            //This table will need a model so we need to set it up and save it into the models directory
            $ir_exists_model = '<?php

    class Image_relationship_model extends active_record
    {

    }

    ?>';

            mkdir ( '../app/models/image_relationship' );
            file_put_contents ( '../app/models/image_relationship/image_relationship_model.php', $ir_exists_model );

            display ( "\nThe image relationship table and model has been made.\n" );
        }
    }

    /**
     * Method to check if the access table exists
     * If it doesnt exist then it will be created, the model will also be created if it doesnt exist
     *
     */
    public function access_table ()
    {
        $admin_exists_query = mysql_query ( "SHOW TABLES LIKE '" . $this->_db_name . "_access'" );
        $admin_exists_count = mysql_num_rows ( $admin_exists_query );

        if ($admin_exists_count == 0) {
            mysql_query ( 'CREATE TABLE `' . $this->_db_name . '_access` (
            `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
            `' . $this->_db_name . '_access_username` VARCHAR(255),
            `' . $this->_db_name . '_access_password` VARCHAR(255) )' ) or die ( mysql_error () );

            //Add in a default user with the username 'admin' and the password 'password'
            mysql_query ( 'INSERT INTO `' . $this->_db_name . '_access` ( `' . $this->_db_name . '_access_username`, `' . $this->_db_name . '_access_password` ) VALUES ( "admin", sha1 ( "password" ) )' );

            $access_model = '<?php

            ?>';

        }
    }
}

$db = new db ( $table, $fields );
$db->connect_mysql ();
$db->check_exists ();
$db->get_query ();
$db->create_table ();
$db->image_table ();
$db->image_relationship_table ();
$db->access_table ();
